apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}-main
  labels:
    app: {{ .Values.fullname }}-main
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullname }}-main
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}-main
    spec:
      containers:
        - name: {{ .Values.containers.main.name }}
          image: "{{ .Values.containers.main.repository }}:{{ .Values.containers.main.tag }}"
          imagePullPolicy: {{ .Values.containers.main.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.main.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}-game
  labels:
    app: {{ .Values.fullname }}-game
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullname }}-game
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}-game
    spec:
      containers:
        - name: {{ .Values.containers.game.name }}
          image: "{{ .Values.containers.game.repository }}:{{ .Values.containers.game.tag }}"
          imagePullPolicy: {{ .Values.containers.game.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.game.port }}
