apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}-main
  labels:
    app: {{ .Values.fullname }}
spec:
  selector:
    app: {{ .Values.fullname }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.mainPort }}
      targetPort: {{ .Values.service.mainTargetPort }}
      name: main
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}-game
  labels:
    app: {{ .Values.fullname }}
spec:
  selector:
    app: {{ .Values.fullname }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.gamePort }}
      targetPort: {{ .Values.service.gameTargetPort }}
      name: game
  type: ClusterIP
