replicaCount: 1

fullname: uwudevs

containers:
  main:
    name: main
    repository: wikimax/uwudev
    tag: latest
    pullPolicy: Always
    port: 3000
  game:
    name: game
    repository: wikimax/uwudev
    tag: latest
    pullPolicy: Always
    port: 3001

service:
  mainPort: 80
  mainTargetPort: 3000
  gamePort: 80
  gameTargetPort: 80

ingress:
  enabled: true
  className: nginx
  host: uwudevs.fr
  tls:
    enabled: true
    secretName: uwudevs-fr-tls
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
